# Do not edit this file
# This file is autogenerated by icon-importer.ts

defmodule Moon.Helpers.Icons do
  @moduledoc false

  @group_names ~w(
      age_limit
      country_flags
      crests
      currencies
      duotones
      icons
      icons_new
      logos
      patterns
    )

  def group_names, do: @group_names

  def list_all do
    ~w(
        age_limit
         country_flags
         crests
         currencies
         duotones
         icons
         icons_new
         logos
         patterns
      )
  end

  def list_age_limit do
    ~w(
          age_limit
        )
  end

  def list_country_flags do
    ~w(
          country_flags
        )
  end

  def list_crests do
    ~w(
          crests
        )
  end

  def list_currencies do
    ~w(
          currencies
        )
  end

  def list_duotones do
    ~w(
          duotones
        )
  end

  def list_icons do
    ~w(
          icons
        )
  end

  def list_icons_new do
    ~w(
          icons_new
        )
  end

  def list_logos do
    ~w(
          logos
        )
  end

  def list_patterns do
    ~w(
          patterns
        )
  end
end
